# Generated by Django 4.2.7 on 2025-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVATTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cvat_task_id",
                    models.IntegerField(
                        help_text="ID da task no CVAT", verbose_name="CVAT Task ID"
                    ),
                ),
                (
                    "cvat_job_id",
                    models.IntegerField(
                        help_text="ID do job no CVAT",
                        unique=True,
                        verbose_name="CVAT Job ID",
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID do projeto no CVAT",
                        null=True,
                        verbose_name="Project ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Projeto",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=255, verbose_name="Nome da Task"),
                ),
                (
                    "assignee",
                    models.CharField(
                        blank=True,
                        help_text="Username do responsável no CVAT",
                        max_length=100,
                        null=True,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Status do job no CVAT",
                        max_length=50,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Estado do job no CVAT",
                        max_length=50,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "manual_annotations",
                    models.IntegerField(
                        default=0,
                        help_text="Total de anotações feitas manualmente",
                        verbose_name="Anotações Manuais",
                    ),
                ),
                (
                    "interpolated_annotations",
                    models.IntegerField(
                        default=0,
                        help_text="Total de anotações interpoladas automaticamente",
                        verbose_name="Anotações Interpoladas",
                    ),
                ),
                (
                    "total_annotations",
                    models.IntegerField(
                        default=0,
                        help_text="Total de anotações (manuais + interpoladas)",
                        verbose_name="Total de Anotações",
                    ),
                ),
                (
                    "cvat_url",
                    models.URLField(
                        blank=True,
                        help_text="Link direto para a task no CVAT",
                        max_length=500,
                        null=True,
                        verbose_name="URL do CVAT",
                    ),
                ),
                (
                    "cvat_data",
                    models.JSONField(
                        blank=True,
                        help_text="Payload completo do CVAT para referência",
                        null=True,
                        verbose_name="Dados do CVAT",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última sincronização",
                        verbose_name="Última Sincronização",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "CVAT Task",
                "verbose_name_plural": "CVAT Tasks",
                "ordering": ["-last_synced_at"],
                "indexes": [
                    models.Index(
                        fields=["cvat_task_id", "cvat_job_id"],
                        name="cvat_sync_c_cvat_ta_e53f46_idx",
                    ),
                    models.Index(
                        fields=["project_id"], name="cvat_sync_c_project_2c17a6_idx"
                    ),
                    models.Index(
                        fields=["assignee"], name="cvat_sync_c_assigne_c273ad_idx"
                    ),
                    models.Index(
                        fields=["status"], name="cvat_sync_c_status_11c745_idx"
                    ),
                ],
            },
        ),
    ]
