# Generated by Django 4.2.7 on 2025-11-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cvat_sync", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Tipo de evento recebido (create, update, delete)",
                        max_length=100,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Dados completos recebidos do webhook",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de Origem"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Recebido em"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "cvat_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="cvat_sync.cvattask",
                        verbose_name="Task CVAT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="cvat_sync_w_event_t_120365_idx"
                    ),
                    models.Index(
                        fields=["status"], name="cvat_sync_w_status_743a9b_idx"
                    ),
                    models.Index(
                        fields=["-received_at"], name="cvat_sync_w_receive_d3b5f7_idx"
                    ),
                ],
            },
        ),
    ]
