# Generated by Django 4.2.7 on 2025-11-13 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cvat_sync", "0002_webhooklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvattask",
            name="last_synced_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Data e hora da última sincronização",
                verbose_name="Última Sincronização",
            ),
        ),
    ]
