# Generated by Django 4.2.7 on 2025-11-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvat_sync", "0003_alter_cvattask_last_synced_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cvattask",
            options={
                "ordering": ["-cvat_job_id"],
                "verbose_name": "CVAT Task",
                "verbose_name_plural": "CVAT Tasks",
            },
        ),
        migrations.AddField(
            model_name="cvattask",
            name="stage",
            field=models.CharField(
                blank=True,
                help_text="Etapa do workflow (annotation, validation, acceptance)",
                max_length=50,
                null=True,
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="cvattask",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="Estado de progresso do job (in progress, completed, etc.)",
                max_length=50,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="cvattask",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Status do job no CVAT (new, validation, completed, etc.)",
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
