# Generated by Django 4.2.7 on 2025-11-14 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cvat_sync", "0004_alter_cvattask_options_cvattask_stage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvattask",
            name="state",
        ),
        migrations.AddField(
            model_name="cvattask",
            name="cvat_state",
            field=models.CharField(
                blank=True,
                help_text="Estado original de progresso do job no CVAT (in progress, completed, etc.)",
                max_length=50,
                null=True,
                verbose_name="Estado CVAT",
            ),
        ),
        migrations.AddField(
            model_name="cvattask",
            name="cvat_status",
            field=models.CharField(
                blank=True,
                help_text="Status original do job no CVAT (new, validation, completed, etc.)",
                max_length=50,
                null=True,
                verbose_name="Status CVAT",
            ),
        ),
        migrations.AddField(
            model_name="cvattask",
            name="data_conclusao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora de conclusão da task",
                null=True,
                verbose_name="Data de Conclusão",
            ),
        ),
        migrations.AddField(
            model_name="cvattask",
            name="data_inicio",
            field=models.DateField(
                blank=True,
                help_text="Data de início da task",
                null=True,
                verbose_name="Data de Início",
            ),
        ),
        migrations.AddField(
            model_name="cvattask",
            name="manual_override",
            field=models.BooleanField(
                default=False,
                help_text="Se True, status não será sobrescrito pelo webhook do CVAT",
                verbose_name="Override Manual",
            ),
        ),
        migrations.AddField(
            model_name="cvattask",
            name="responsavel",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuários responsáveis por esta task",
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsáveis",
            ),
        ),
        migrations.AlterField(
            model_name="cvattask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_andamento", "Em Andamento"),
                    ("conferindo", "Conferindo"),
                    ("feito", "Feito"),
                    ("revisado", "Revisado"),
                ],
                default="pendente",
                help_text="Status atual da task no sistema",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
